export const translations = {
    en: {
        pageTitle: "Gaigle - AI-Powered Search",
        searchPlaceholder: "Search with Gaigle...",
        loadingText: "Searching with AI...",
        quickAnswer: "Quick Answer",
        noResults: "No results found. Try a different query.",
        errorMessage: "An unknown error occurred while searching. Please try again.",
        networkError: "Network error. Please check your internet connection.",
        apiError: "API server error. Please try again later.",
        apiTimeout: "The server is taking too long to respond",
        invalidRequest: "Invalid search query",
        serverError: "Server is currently unavailable",
        rateLimitExceeded: "Too many requests. Please wait before trying again.",
        switchToRussian: "Русский",
        switchToEnglish: "English",
        loadMore: "More",
        makeLonger: "Make longer",
        customPrompt: "Ask a follow-up question...",
        disclaimer: "This site is not affiliated with or produced by Google Corporation. All answers are generated by AI and may not be 100% accurate."
    },
    ru: {
        pageTitle: "Gaigle - Поиск с ИИ",
        searchPlaceholder: "Поиск с помощью Gaigle...",
        loadingText: "Ищем с помощью ИИ...",
        quickAnswer: "Быстрый ответ",
        noResults: "Ничего не найдено. Попробуйте другой запрос.",
        errorMessage: "Произошла ошибка при поиске. Пожалуйста, попробуйте ещё раз.",
        networkError: "Ошибка сети. Пожалуйста, проверьте интернет-соединение.",
        apiError: "Ошибка сервера API. Пожалуйста, попробуйте позже.",
        apiTimeout: "Сервер слишком долго отвечает",
        invalidRequest: "Некорректный поисковый запрос",
        serverError: "Сервер временно недоступен",
        rateLimitExceeded: "Слишком много запросов. Пожалуйста, подождите перед повторной попыткой.",
        switchToRussian: "Русский",
        switchToEnglish: "English",
        loadMore: "Ещё",
        makeLonger: "Длиннее",
        customPrompt: "Уточняющий вопрос...",
        disclaimer: "Данный сайт никак не связан с корпорацией Google, и не производится ей. Все ответы делаются нейросетью и не могут быть верны на 100%."
    }
};

export const russianSpeakingCountries = ["RU", "BY", "UA", "KZ"];
